- name: install and run nginx
  hosts: web  # we can't give multiple groups here, we have to give single here.
  become: yes # -b become root user
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes