- name: plabook
  hosts: web
  become: yes # -b
  task:
    - name: install nginx server
      ansible.builtin.package: #dnf will work for only redHat but this is hetrogenous
        name: nginx
        state: present
    - name: start nginx sever
      ansible.builtin.service:
        name: start the service
        state: started
        enabled: yes
