- name: PLAY1
  hosts: local # managing own node
  connection: local # Ansible managing its own node, no need of ssh credentials
  tasks:
  - name: PLAY1 and TASK1
    ansible.builtin.debug:
      msg: "Hello from PLAY1 and TASK1"

- name: PLAY2
  hosts: local
  connection: local # managing its own node, no need of ssh credentials
  tasks:
  - name: PLAY2 and TASK1
    ansible.builtin.debug:
      msg: "Hello from PLAY2 and TASK1"