- name: variables from files
  hosts: local
  connection: local
  vars_prompt: # we can use this for confidentaional information
  - name: COURSE # variable name
    prompt: Please enter course name
    private: false # it is not confidential information, the typed information will be visible
  - name: DURATION
    prompt: Pleae enter duration
    private: false
  - name: TRAINER
    prompt: Please enter trainer name
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"