- name: install packages
  hosts: web
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: "git", state: "present" }
        - { name: "mysql", state: "absent" }
        - { name: "gcc", state: "present" }
        - { name: "zip", state: "absent" }
# these advance looping, where we can install and uninstall package same time
# in loop we can pass a name or object also, here we are passing object.
